### ISSUE TITLE
Problem picutre is null when returning to MainActivity in different orientation

### ISSUE THREAD

**Issue by ghost** [WatchDoges/WatchDoge#107]
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
W/System.err:     at doge.watchdoge.converters.ImageConverters.bitmapToPNG(ImageConverters.java:26)
W/System.err:     at doge.watchdoge.activities.MainActivity.onActivityResult(MainActivity.java:281)
W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:6490)
W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:3794)
W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3146)
W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3191)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2529)
W/System.err:     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4176)
W/System.err:     at android.app.ActivityThread.access$1000(ActivityThread.java:154)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1397)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:234)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5526)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
W/System: ClassLoader referenced unknown path: /system/framework/tcmclient.jar

**Comment by Fgranen** [comment]
problem arises when changing from landscape to portrait mode, but not the other way around. New activity is created before onActivityResult is called, making the file reference Null and fails making problem picture.
